name: optimal_transport
channels:
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
- gurobi
- cvxgrp
- mosek
- conda-forge
- defaults
dependencies:
- python=3.6.2=0
- jupyter=1.0.0=py36_3
- numpy=1.13.1=py36_0
- scipy=0.19.1=np113py36_0
- matplotlib=2.0.2=np113py36_0
- mosek=8.1.34=py36h70ad355_0
- gurobi=7.5.1=py36_0
- cvxpy=0.4.9=py36_0
- networkx=2.0=py36h7e96fb8_0
- memory_profiler=0.43=py36_0

